import { ApiResponse } from '../types';

export const fetchMatches = async (): Promise<ApiResponse> => {
  try {
    // Fetch the static JSON file generated by the build script or GitHub Action
    const response = await fetch(`${import.meta.env.BASE_URL}matches.json`);
    
    if (response.status !== 200) {
      throw new Error(`无法获取赛程数据: ${response.status}`);
    }

    const result = await response.json();
    
    if (!result || !Array.isArray(result.matches)) {
      throw new Error('赛程数据格式不正确');
    }

    return {
      matches: result.matches,
      lastUpdated: result.lastUpdated,
      source: result.source || 'static'
    };
  } catch (error) {
    console.error('获取赛程出错:', error);
    throw error;
  }
};
